<?php
/**
 * Created by PhpStorm.
 * User: HP
 * Date: 20/11/2018
 * Time: 15:08
 */

class Avion extends Vehicule
{
    private $nbMoteurs;
    public function __construct($marque, $dateAchat, $prixAchat, $prixCourant,$nbMoteurs)
    {
        parent :: __construct($marque,$dateAchat,$prixAchat,$prixCourant);
        $this->nbMoteurs= $nbMoteurs;
    }
public function  SeDeplacer()
{
 echo "<br> Je vole dans les airs <br>";
}
public function affiche()
{
    parent::affiche(); // TODO: Change the autogenerated stub
    echo "<br> Je suis un avion et j'ai $this->nbMoteurs moteurs <br>";
}
public function __destruct()
{
    parent::__destruct(); // TODO: Change the autogenerated stub
    echo "<br> Avion ".parent::getMarque()." détruit<br>";
}
}