<?php
/**
 * Created by PhpStorm.
 * User: HP
 * Date: 20/11/2018
 * Time: 15:06
 */

class Voiture extends Vehicule
{
    private $nbPortes;

    /**
     * Voiture constructor.
     * @param $nbPortes
     */
    public function __construct($marque, $dateAchat, $prixAchat, $prixCourant, $nbPortes)
    {
        parent :: __construct($marque,$dateAchat,$prixAchat,$prixCourant);
        $this->nbPortes = $nbPortes;
    }

    public function SeDeplacer(){
        echo "<br> Je roule sur la chaussée <br>";
    }
    public function affiche()
    {
        parent::affiche(); // TODO: Change the autogenerated stub
        echo "je suis une voiture, j'ai $this->nbPortes portes";

    }
    public function taxeVente ()
    {
        $tv= $this->getPrixAchat()*0.05;
        return $tv;
    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
        echo "<br> Voiture ". parent::getMarque()."  détruite <br>";
    }
}
?>